### ISSUE TITLE
Lifecycle Methods

### ISSUE THREAD

**Issue by adampielach** [delprzemo/react-cheatsheet#1]
I would fix section with the recent information that's been around for quite a while which is `UNSAFE_` prefix, not to mention it's overall deprecation of all `will` lifecycle methods. Also, we have new lifecycle methods that are not used so often but are worth mentioning I think - `getDerivedStateFromProps` and `getSnapshotBeforeUpdate`.

**Comment by delprzemo** [comment]
Thank you for pointing that. Cheatsheet updated

**Comment by delprzemo** [comment]
Closing
