### ISSUE TITLE
Conditional element 4 option suggestion 

### ISSUE THREAD

**Issue by gregorh1** [delprzemo/react-cheatsheet#2]
Suggestion: 

## Conditional element 
...
**Option 4:**
```jsx
{this.state.isShow  &&  <div> Here is element </div>}
```

**Comment by gregorh1** [comment]
I have tried to create pull request, but could not push the branch - no permission...

**Comment by delprzemo** [comment]
You can do it by forking a repository - https://kbroman.org/github_tutorial/pages/fork.html
Anyway, I've already performed a change. Thank you for pointing that

**Comment by delprzemo** [comment]
Added new option
